www/ContactOrganization.js

Updated the comments for ContactOrganization constructor.

Fix for CB-4946

---

tests/tests.js

https://issues.apache.org/jira/browse/CB-9056

CB-9056 Increased timeout of failing tests

---

tests/tests.js

https://issues.apache.org/jira/browse/CB-9579

CB-9579 Fixed failed tests when "DeleteMe" contact already exists

---

src/ios/CDVContact.m

https://issues.apache.org/jira/browse/CB-3950

CB-3950 Do not replace custom labels with "Other" on contact save

---

src/android/ContactAccessorSdk5.java

https://issues.apache.org/jira/browse/CB-10094

CB-10094 Android: Fixed empty string comparison

---

src/android/ContactAccessorSdk5.java
tests/tests.js

This fixes issue with updating existing contact, described in [CB-5308](https://issues.apache.org/jira/browse/CB-5308)

CB-5308 Return rawId instead of id when modifying existing contact

---

src/android/ContactManager.java

We currently don't request the permission and get a SecurityException when the Activity returns on Marshmallow.

CB-10148: Added READ_CONTACTS permission request when picking contacts

---

tests/tests.js

https://issues.apache.org/jira/browse/CB-10117

CB-10117 Added new tests

---

.gitignore
.jshintrc
.travis.yml
README.md
package.json
src/blackberry10/contactUtils.js
src/blackberry10/index.js
src/firefoxos/ContactsProxy.js
src/windows/ContactProxy.js
src/windows8/ContactProxy.js
tests/tests.js
www/contacts.js

Fixed contacts.spec.5
[Jira issue](https://issues.apache.org/jira/browse/CB-10636)

CB-10636 Add JSHint for plugins

---

plugin.xml
tests/tests.js
www/Contact.js
www/contacts.js
www/convertUtils.js

Converting `birthday` stored as string internally to `Date` to align with the plugin API.
Added a corresponding test for find method.
[Jira issue](https://issues.apache.org/jira/browse/CB-8115)

CB-8115 incorrect birthday saved to phonebook using Contacts Plugin

---

appium-tests/common/common.spec.js
appium-tests/helpers/contactsHelper.js

https://issues.apache.org/jira/browse/CB-10399

CB-10399 Added Appium tests

---

appium-tests/common/common.spec.js

https://issues.apache.org/jira/browse/CB-11033

CB-11033 Appium tests: Increased the timeout for updating the contact

---

src/android/ContactAccessorSdk5.java
tests/tests.js

Added a corresponding test
[Jira issue](https://issues.apache.org/jira/browse/CB-10985)

CB-10985 Android sets type to -1 for ims

---

appium-tests/common/common.spec.js

https://issues.apache.org/jira/browse/CB-11166

CB-11166 Added an Appium tests to check for contact's birthday

---

appium-tests/common/common.spec.js

Please review @alsorokin !
iOS.
When running UI automation tests in iOS, if you are running Xcode 8 or newer (which you must have to run tests on iOS 10), you _must_ leverage Apple's new UI automation framework, XCUITest. The current tests are written assuming the older iOS UI automation framework, UIAutomation. 
These changes move the appium test code so it is compatible with both:
- 9.3 and earlier iOS automation framework, UIAutomation
- 10.0+ iOS automation framework, XCUITest
The main changes include:
- leverages finding elements in native iOS land using the name selector, which also happens to be faster than XPath selectors. This was required as the test case for Unicode-based elements with XPath-based selection did _not_ work under XCUITest.
- Appium has a handy capability called …

[Appium] Add support for iOS' XCUITest automation library

---

appium-tests/common/common.spec.js

Android
Makes Appium tests honor the selenium quirk which leads to stack overflow on Android 6 and 7.
Also, adds a permission dialog buster for Appium tests.
Ran tests on Sauce Labs for Android 6 and 7 emulators.

CB-12622: (android) Adapt Appium tests for Android 6 and 7

---

package.json

CB-13521 (all): Add 'protective' entry to cordovaDependencies

---

README.md
plugin.xml

CB-13522 (iOS): Remove usage description

---

README.md

Added a deprecation notice to the README.

CB-13062:Added deprecation notice to README

---

.travis.yml

CB-13759: Add build-tools-26.0.2 to travis
